MvcOnlineCommercialAutomation/Controllers/CariController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using MvcOnlineCommercialAutomation.Models.Class;
using MvcOnlineCommercialAutomation.Models.Classes;

namespace MvcOnlineCommercialAutomation.Controllers
{
    public class CariController : Controller
    {
        Context context = new Context();
        // GET: Cari
        public ActionResult Index()
        {
            var values = context.TblCarilers.Where(x=>x.Status==true).ToList();
            return View(values);
        }
        [HttpGet]
        public ActionResult AddCari()
        {
            return View();
        }
        [HttpPost]
        public ActionResult AddCari(Cariler c)
        {
            c.Status = true;
            context.TblCarilers.Add(c);
            context.SaveChanges();
            return RedirectToAction("Index");
        }
        public ActionResult DeleteCari(int id)
        {
            var p = context.TblCarilers.Find(id);
            p.Status = false;
            context.SaveChanges();
            return RedirectToAction("Index");
        }
        
        public ActionResult GetCari(int id)
        {
            var p = context.TblCarilers.Find(id);
            return View("GetCari", p);
        }
        
        public ActionResult UpdateCari(Cariler cari)
        {
            if (!ModelState.IsValid)
            {
                return View("GetCari");
            }
            var p = context.TblCarilers.Find(cari.CariId);
            p.CariName = cari.CariName;
            p.CariSurname = cari.CariSurname;
            p.CariCity = cari.CariCity;
            p.CariMail = cari.CariMail;
            context.SaveChanges();
            return RedirectToAction("Index");
        }
        public ActionResult CariSale(int id)
        {
            var values = context.TblSaleOperation.Where(x => x.CariId == id).ToList();
            var cr = context.TblCarilers.Where(x => x.CariId == id).Select(y => y.CariName + " " + y.CariSurname).FirstOrDefault();
            ViewBag.cari = cr;
            return View(values);
        }
    }
}

MvcOnlineCommercialAutomation/Views/Cari/AddCari.cshtml
@model MvcOnlineCommercialAutomation.Models.Class.Cariler
@{
    ViewBag.Title = "AddCari";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<br />
<h2>Yeni Ürün Cari Sayfası</h2>
<br />

<form method="post" class="form-group">
    @Html.Label("Cari Adı")
    @Html.TextBoxFor(x => x.CariName, new { @class = "form-control" })
    <br />
    @Html.Label("Cari Soyadı")
    @Html.TextBoxFor(x => x.CariSurname, new { @class = "form-control" })
    <br />
    @Html.Label("Cari Şehir")
    @Html.TextBoxFor(x => x.CariCity, new { @class = "form-control" })
    <br />
    @Html.Label("Cari Mail")
    @Html.TextBoxFor(x => x.CariMail, new { @class = "form-control" })
    <br />
   
    <button class="btn btn-primary">Kaydet</button>
</form>

MvcOnlineCommercialAutomation/Views/Cari/CariSale.cshtml
@using MvcOnlineCommercialAutomation.Models.Class
@model List<SaleOperation>
@{
    ViewBag.Title = "CariSale";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<br />
<h2>Cari Satış</h2>
<br />

<ol class="breadcrumb mb-4">
    <li class="breadcrumb-item active"><b>Cari Adı</b>: @ViewBag.cari</li>
</ol>
<br />
<table class="table table-condensed">
    <tr>
        <th>Satış Id</th>
        <th>Ürün</th>
        <th>Personel</th>
        <th>Fiyat</th>
        <th>Adet</th>
        <th>Toplam</th>
        <th>Tarih</th>
        <th>Yazdır</th>
    </tr>
    @foreach (var item in Model)
    {
        <tr>
            <td>@item.SaleId</td>
            <td>@item.Product.ProductName</td>
            <td>@item.Employee.EmployeeName @item.Employee.EmployeeSurname</td>
            <td>@item.Price</td>
            <td>@item.Adet</td>
            <td>@item.TotalPrice</td>
            <td>@item.Date</td>
            <td><a href="#" class="btn btn-default" style="background-color:dodgerblue; color:white;">Yazdır</a></td>
        </tr>
    }
</table>

MvcOnlineCommercialAutomation/Views/Cari/GetCari.cshtml
@model MvcOnlineCommercialAutomation.Models.Class.Cariler
@{
    ViewBag.Title = "GetCari";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<br />
<h2>Cari Güncelleme Sayfası</h2>
<br />

@using (Html.BeginForm("UpdateCari", "Cari", FormMethod.Post))
{
    @Html.HiddenFor(x => x.CariId)
    @Html.Label("Cari Adı")
    @Html.TextBoxFor(x => x.CariName, new { @class = "form-control" })
    @Html.ValidationMessageFor(x => x.CariName, "", new { @style = "color:red" })
    <br />
    @Html.Label("Cari Soyadı")
    @Html.TextBoxFor(x => x.CariSurname, new { @class = "form-control" })
    @Html.ValidationMessageFor(x => x.CariSurname, "", new { @style = "color:red" })

    <br />
    @Html.Label("Cari Şehir")
    @Html.TextBoxFor(x => x.CariCity, new { @class = "form-control" })
    <br />
    @Html.Label("Cari Mail")
    @Html.TextBoxFor(x => x.CariMail, new { @class = "form-control" })
    <br />

    @Html.Label("Cari Durum")
    @Html.TextBoxFor(x => x.Status, new { @class = "form-control" })
    <br />
    <button class="btn btn-primary">Kaydet</button>
}

MvcOnlineCommercialAutomation/Views/Cari/Index.cshtml
@using MvcOnlineCommercialAutomation.Models.Class;
@model List<Cariler>
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<br />
<table class="table table-striped">
    <tr>
        <th>Id</th>
        <th>Ad</th>
        <th>Soyad</th>
        <th>Şehir</th>
        <th>Mail</th>
        <th>Sil</th>
        <th>Güncelle</th>
        <th>Detaylar</th>
    </tr>
    @foreach (var item in Model)
    {
        <tr>
            <td>@item.CariId</td>
            <td>@item.CariName</td>
            <td>@item.CariSurname</td>
            <td>@item.CariCity</td>
            <td>@item.CariMail</td>
            <td><a href="/Cari/DeleteCari/@item.CariId/" class="btn btn-danger">Sil</a></td>
            <td><a href="/Cari/GetCari/@item.CariId/" class="btn btn-warning">Güncelle</a></td>
            <td><a href="/Cari/CariSale/@item.CariId/" class="btn btn-default" style="background-color:lightcoral; color:white">Satış Geçmişi</a></td>
            <td></td>
        </tr>
    }
</table>
<a href="/Cari/AddCari/" class="btn btn-primary">Yeni Cari Ekle</a>